#NAME: Prithvi Kannan
#EMAIL: prithvi.kannan@gmail.com
#ID: 405110096

.SILENT:

default: dist

dist: README
	tar -czvf lab4a-405110096.tar.gz build_run.png  connected.png  copy.png  git.png Makefile  my_beaglebone.jpg  README

clean:
	rm -rf *.tar.gz
